# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fd661f033aaf496f5bfcadf479513c7d744d9ea904822c0d1ebbd46bb0fdd7625e1ea074d2488b671f42887d4008e7bd070c7fd132b231fed0e8ef8f2964cf5

test:
  secret_key_base: addf6ee861c5b2c22e4bdb79df992b95266a20ffa1b39c16407033dfa8352d408e9fe20da88c420da41e0407aafa14b05471a7d720d183174cb6d1265fa7ef16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
